#' Reproducible R code export
#'
#' Turns an analysis session into a standalone, runnable R script that
#' reproduces the pipeline with RNAflow's public functions -- ready to drop
#' into a Methods section or a supplementary file. Pure string generation,
#' no side effects.
#'
#' @name export_code
#' @keywords internal
NULL

#' Sanitize a contrast label into a valid R object suffix
#' @keywords internal
r_name <- function(x) {
  x <- gsub("[^A-Za-z0-9]+", "_", x)
  x <- gsub("^_+|_+$", "", x)
  if (!nzchar(x)) x <- "contrast"
  x
}

#' Generate a reproducible R script for an analysis
#'
#' @param project a project list (from [empty_project()] / the app session);
#'   uses `$organism` and `$contrasts` (the contrast store)
#' @param counts_path,metadata_path paths written into the `read_*` calls
#' @param generated optional timestamp string to stamp in the header
#' @return a single character string containing the R script
#' @export
generate_r_script <- function(project,
                              counts_path = "counts.csv",
                              metadata_path = "metadata.csv",
                              generated = NULL) {
  organism <- project$organism %||% "human"
  store    <- project$contrasts %||% list()
  ver <- tryCatch(as.character(utils::packageVersion("RNAflow")),
                  error = function(e) "dev")

  L <- character(0)
  add <- function(...) L <<- c(L, ...)

  add(sprintf("# RNAflow reproducible analysis script"),
      sprintf("# Generated by RNAflow v%s%s", ver,
              if (!is.null(generated)) paste0(" on ", generated) else ""),
      "# DE calls reflect each saved contrast (design, covariates, shrinkage).",
      "# Enrichment / WGCNA use the settings actually run when those were",
      "# recorded; otherwise example defaults are emitted -- edit as needed.",
      "",
      "library(RNAflow)",
      "",
      "## 1. Load and validate inputs -------------------------------------------",
      sprintf('counts   <- read_counts("%s")', counts_path),
      sprintf('meta     <- read_metadata("%s", counts_samples = colnames(counts))',
              metadata_path),
      sprintf('organism <- "%s"', organism),
      "")

  # ---- Differential expression, one call per stored contrast ----
  add("## 2. Differential expression (DESeq2) -----------------------------------")
  var_names <- character(0)
  if (length(store) == 0) {
    add("# No contrasts were saved in this session; template call below:",
        "res_1 <- run_deseq2(counts, meta, design = ~condition,",
        '                    contrast = c("condition", "Treatment", "Control"))')
    var_names <- "res_1"
  } else {
    for (i in seq_along(store)) {
      lbl <- names(store)[i]
      p <- store[[i]]$params %||% list()
      vn <- paste0("res_", r_name(lbl))
      var_names <- c(var_names, vn)
      if (!is.null(p$design_var)) {
        design_terms <- c(p$covariates, p$design_var)   # covariates first
        add(sprintf("# %s", lbl),
            sprintf("%s <- run_deseq2(", vn),
            "  counts, meta,",
            sprintf("  design   = ~%s,", paste(design_terms, collapse = " + ")),
            sprintf('  contrast = c("%s", "%s", "%s"),',
                    p$design_var, p$treated, p$reference),
            sprintf("  shrink = %s, min_count = %s, alpha = %s",
                    isTRUE(p$shrink), p$min_count %||% 10, p$alpha %||% 0.05),
            ")", "")
      } else {
        add(sprintf('# %s (uploaded / parameters unknown)', lbl),
            sprintf("# %s <- <your DE results data.frame>", vn), "")
      }
    }
  }
  add("")

  # ---- Figures + multi-contrast ----
  ex <- var_names[1]
  add("## 3. Figures & multi-contrast comparison -------------------------------",
      sprintf("p_volcano <- fig_volcano(%s, lfc_thr = 1, padj_thr = 0.05,", ex),
      '                         mode = "publication")',
      'save_ggplot(p_volcano, "volcano.pdf", "pdf", w = 5, h = 4)',
      "")
  if (length(var_names) >= 2) {
    items <- paste(sprintf('  `%s` = %s', names(store), var_names),
                   collapse = ",\n")
    add("# Compare contrasts",
        paste0("contrasts <- list(\n", items, "\n)"),
        "fig_upset(contrast_sig_sets(contrasts, padj_thr = 0.05, lfc_thr = 1))",
        'fig_lfc_heatmap(contrasts, gene_src = "sig_union")',
        "")
  }

  # ---- Enrichment (exact settings when recorded, else a template) ----
  add("## 4. Functional enrichment ---------------------------------------------")
  en <- project$enrichment
  if (is.list(en) && length(en) && !is.null(en$method) && en$method == "gsea") {
    sub <- if (!is.null(en$subcollection))
      sprintf(', subcollection = "%s"', en$subcollection) else ""
    add(sprintf('gene_sets <- get_gene_sets(organism, collection = "%s"%s)',
                en$collection, sub),
        sprintf('gsea <- run_gsea(%s, gene_sets, rank_by = "%s")', ex, en$rank_by),
        "fig_enrich_dot(gsea)", "")
  } else if (is.list(en) && length(en) && !is.null(en$method) && en$method == "ora") {
    add(sprintf('sig <- contrast_sig_genes(%s, padj_thr = %s, lfc_thr = %s, direction = "%s")',
                ex, en$padj %||% 0.05, en$lfc %||% 1, en$direction %||% "either"),
        sprintf('ora <- run_ora(sig, organism, db = "%s", ont = "%s", universe = %s$gene)',
                en$db %||% "GO", en$ont %||% "BP", ex),
        "fig_enrich_bar(ora)", "")
  } else {
    add("# (no enrichment run recorded -- example with default settings)",
        'gene_sets <- get_gene_sets(organism, collection = "H")',
        sprintf('gsea <- run_gsea(%s, gene_sets, rank_by = "stat")', ex),
        "fig_enrich_dot(gsea)",
        sprintf('sig <- contrast_sig_genes(%s, padj_thr = 0.05, lfc_thr = 1)', ex),
        sprintf('ora <- run_ora(sig, organism, db = "GO", ont = "BP", universe = %s$gene)', ex),
        "fig_enrich_bar(ora)", "")
  }

  # ---- WGCNA (exact settings when recorded, else a template) ----
  add("## 5. Co-expression network (WGCNA) -------------------------------------",
      'norm    <- normalize_counts(counts, meta, method = "vst")')
  wg <- project$wgcna
  if (is.list(wg) && length(wg) && !is.null(wg$power)) {
    add(sprintf("datExpr <- wgcna_datexpr(norm, n_genes = %s)", wg$n_genes %||% 3000),
        sprintf('wg <- run_wgcna(datExpr, power = %s, network_type = "%s",',
                wg$power, wg$network_type %||% "signed"),
        sprintf("                min_module_size = %s, merge_cut_height = %s, deep_split = %s)",
                wg$min_module_size %||% 30, wg$merge_cut_height %||% 0.25,
                wg$deep_split %||% 2))
  } else {
    add("# (no module run recorded -- example with an auto-picked power)",
        "datExpr <- wgcna_datexpr(norm, n_genes = 3000)",
        "sft     <- wgcna_pick_power(datExpr)",
        "wg      <- run_wgcna(datExpr, power = sft$suggested)")
  }
  add("traits  <- build_traits(meta, rownames(datExpr))",
      "fig_module_trait(module_trait_cor(wg$MEs, traits))",
      "")

  # ---- Signatures (GSVA/ssGSEA): exact collection/method when recorded ----
  add("## 6. Signatures (GSVA / ssGSEA) ---------------------------------------",
      "# NOTE: the app maps gene IDs to symbols before scoring; ensure",
      "#       rownames(norm) are gene symbols to reproduce this exactly.")
  sg <- project$signatures
  if (is.list(sg) && length(sg) && !is.null(sg$collection)) {
    cc  <- ENRICH_COLLECTIONS[[sg$collection]]
    sub <- if (!is.null(cc$sub)) sprintf(', subcollection = "%s"', cc$sub) else ""
    add(sprintf('gene_sets <- get_gene_sets(organism, collection = "%s"%s)',
                cc$collection %||% "H", sub),
        sprintf('scores    <- run_gsva(norm, gene_sets, method = "%s")',
                sg$method %||% "gsva"),
        "fig_gsva_heatmap(scores, meta)", "")
  } else {
    add("# (no signatures run recorded -- example with Hallmark + GSVA)",
        'gene_sets <- get_gene_sets(organism, collection = "H")',
        'scores    <- run_gsva(norm, gene_sets, method = "gsva")',
        "fig_gsva_heatmap(scores, meta)", "")
  }

  add("## 7. Session information -----------------------------------------------",
      "sessionInfo()",
      "")

  paste(L, collapse = "\n")
}
