#' Reproducible R code export
#'
#' Turns an analysis session into a standalone, runnable R script that
#' reproduces the pipeline with RNAflow's public functions -- ready to drop
#' into a Methods section or a supplementary file. Pure string generation,
#' no side effects.
#'
#' @name export_code
#' @keywords internal
NULL

#' Sanitize a contrast label into a valid R object suffix
#' @keywords internal
r_name <- function(x) {
  x <- gsub("[^A-Za-z0-9]+", "_", x)
  x <- gsub("^_+|_+$", "", x)
  if (!nzchar(x)) x <- "contrast"
  x
}

#' Generate a reproducible R script for an analysis
#'
#' @param project a project list (from [empty_project()] / the app session);
#'   uses `$organism` and `$contrasts` (the contrast store)
#' @param counts_path,metadata_path paths written into the `read_*` calls
#' @param generated optional timestamp string to stamp in the header
#' @return a single character string containing the R script
#' @export
generate_r_script <- function(project,
                              counts_path = "counts.csv",
                              metadata_path = "metadata.csv",
                              generated = NULL) {
  organism <- project$organism %||% "human"
  store    <- project$contrasts %||% list()
  ver <- tryCatch(as.character(utils::packageVersion("RNAflow")),
                  error = function(e) "dev")

  L <- character(0)
  add <- function(...) L <<- c(L, ...)

  add(sprintf("# RNAflow reproducible analysis script"),
      sprintf("# Generated by RNAflow v%s%s", ver,
              if (!is.null(generated)) paste0(" on ", generated) else ""),
      "# Reproduces the analysis with RNAflow's public API.",
      "",
      "library(RNAflow)",
      "",
      "## 1. Load and validate inputs -------------------------------------------",
      sprintf('counts   <- read_counts("%s")', counts_path),
      sprintf('meta     <- read_metadata("%s", counts_samples = colnames(counts))',
              metadata_path),
      sprintf('organism <- "%s"', organism),
      "")

  # ---- Differential expression, one call per stored contrast ----
  add("## 2. Differential expression (DESeq2) -----------------------------------")
  var_names <- character(0)
  if (length(store) == 0) {
    add("# No contrasts were saved in this session; template call below:",
        "res_1 <- run_deseq2(counts, meta, design = ~condition,",
        '                    contrast = c("condition", "Treatment", "Control"))')
    var_names <- "res_1"
  } else {
    for (i in seq_along(store)) {
      lbl <- names(store)[i]
      p <- store[[i]]$params %||% list()
      vn <- paste0("res_", r_name(lbl))
      var_names <- c(var_names, vn)
      if (!is.null(p$design_var)) {
        add(sprintf("# %s", lbl),
            sprintf("%s <- run_deseq2(", vn),
            "  counts, meta,",
            sprintf("  design   = ~%s,", p$design_var),
            sprintf('  contrast = c("%s", "%s", "%s"),',
                    p$design_var, p$treated, p$reference),
            sprintf("  shrink = %s, min_count = %s, alpha = %s",
                    isTRUE(p$shrink), p$min_count %||% 10, p$alpha %||% 0.05),
            ")", "")
      } else {
        add(sprintf('# %s (uploaded / parameters unknown)', lbl),
            sprintf("# %s <- <your DE results data.frame>", vn), "")
      }
    }
  }
  add("")

  # ---- Figures + multi-contrast ----
  ex <- var_names[1]
  add("## 3. Figures & multi-contrast comparison -------------------------------",
      sprintf("p_volcano <- fig_volcano(%s, lfc_thr = 1, padj_thr = 0.05,", ex),
      '                         mode = "publication")',
      'save_ggplot(p_volcano, "volcano.pdf", "pdf", w = 5, h = 4)',
      "")
  if (length(var_names) >= 2) {
    items <- paste(sprintf('  `%s` = %s', names(store), var_names),
                   collapse = ",\n")
    add("# Compare contrasts",
        paste0("contrasts <- list(\n", items, "\n)"),
        "fig_upset(contrast_sig_sets(contrasts, padj_thr = 0.05, lfc_thr = 1))",
        'fig_lfc_heatmap(contrasts, gene_src = "sig_union")',
        "")
  }

  # ---- Enrichment ----
  add("## 4. Functional enrichment (GSEA + ORA) --------------------------------",
      'gene_sets <- get_gene_sets(organism, collection = "H")',
      sprintf('gsea      <- run_gsea(%s, gene_sets, rank_by = "stat")', ex),
      "fig_enrich_dot(gsea)",
      sprintf('sig <- contrast_sig_genes(%s, padj_thr = 0.05, lfc_thr = 1)', ex),
      'ora <- run_ora(sig, organism, db = "GO", ont = "BP", universe = ' ,
      sprintf('               %s$gene)', ex),
      "fig_enrich_bar(ora)",
      "")

  # ---- WGCNA ----
  add("## 5. Co-expression network (WGCNA) -------------------------------------",
      'norm    <- normalize_counts(counts, meta, method = "vst")',
      "datExpr <- wgcna_datexpr(norm, n_genes = 3000)",
      "sft     <- wgcna_pick_power(datExpr)",
      "wg      <- run_wgcna(datExpr, power = sft$suggested)",
      "traits  <- build_traits(meta, rownames(datExpr))",
      "fig_module_trait(module_trait_cor(wg$MEs, traits))",
      "",
      "## 6. Session information -----------------------------------------------",
      "sessionInfo()",
      "")

  paste(L, collapse = "\n")
}
